language: julia
os:
  - linux
  - osx
julia:
  - nightly
  - 1.0
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
before_script:
    - cp test/Manifest.toml .
    - julia -e "using Pkg; Pkg.instantiate()"



after_success:
    - julia -e 'cd(Pkg.dir("CompactTranslatesDict")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
