# This file is machine-generated - editing it directly is not advised

[[BasisFunctions]]
git-tree-sha1 = "b8cb8e4bba4f9fbb4937b4bb205b7bd0900da516"
repo-rev = "development"
repo-url = "https://github.com/daanhb/BasisFunctions.jl"
uuid = "4343a256-5453-507d-8aad-01a9d7189916"
version = "0.0.0"

[[CardinalBSplines]]
git-tree-sha1 = "356da9b327a941b9a8dc19d2ef03c78e54ca6f68"
repo-rev = "master"
repo-url = "https://github.com/vincentcp/CardinalBSplines"
uuid = "87d49508-7ad8-11e8-0eda-cb6920b58870"
version = "0.0.0"
